version: '3.9'

services:
  django:
    build: ./app
    command: >
      /bin/sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev

  rabbitmq:
    restart: always
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  celery:
    build: ./app
    command: celery -A my_project worker -l info
    volumes:
      - ./app/:/code
    depends_on:
      - rabbitmq

  celery-beat:
    build: ./app
    command: celery -A my_project beat -l info
    volumes:
      - ./app/:/code
    depends_on:
      - rabbitmq
